### ISSUE TITLE
This does not seem to be a WordPress install?

### ISSUE THREAD

**Issue by jigsawsoul** [dword-design/wp-cli-ssh-command#1]
```Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.```

I am trying to use this command to open ssh to be able to run any command directly on the server, although I am receiving the above error. 

I am running the following `wp ssh @mefirst.staging`

Although when using a built-in command e.g. `wp @mefirst.staging plugin list` this functions correctly as intended.

Could you please assist, many thanks.

**Comment by dword-design** [comment]
Hey jigsawsoul,

can you send me your wp-cli.yml? You can of course obfuscate your credentials, I just need to know how it is structured. For me the ssh connect works fine.

**Comment by jigsawsoul** [comment]
Thanks for replying,

My global config.yml file has the following:

@mefirst.staging:
  ssh: *****
  path: /mnt/data/home/master/applications/mefirst_staging/public_html

@mefirst.production:
  ssh: *****
  path: /mnt/data/home/master/applications/mefirst/public_html

**Comment by dword-design** [comment]
That's an odd thing. The config looks ok for me. Still I cannot reproduce it with my machine, I'm sorry. Maybe you find a solution and contribute to this project.
